# Generated by Django 2.1.7 on 2019-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dianping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('shopname', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('score1', models.TextField(blank=True, null=True)),
                ('score2', models.TextField(blank=True, null=True)),
                ('score3', models.TextField(blank=True, null=True)),
                ('rec1', models.TextField(blank=True, null=True)),
                ('rec2', models.TextField(blank=True, null=True)),
                ('rec3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dianping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DianpingLoc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.TextField(blank=True, null=True)),
                ('shopname', models.TextField(blank=True, null=True)),
                ('lng', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('score1', models.TextField(blank=True, null=True)),
                ('score2', models.TextField(blank=True, null=True)),
                ('score3', models.TextField(blank=True, null=True)),
                ('rec1', models.TextField(blank=True, null=True)),
                ('rec2', models.TextField(blank=True, null=True)),
                ('rec3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dianping_loc',
                'managed': False,
            },
        ),
    ]
